services:

  portainer:
        container_name: portainer
        hostname: portainer
        image: portainer/portainer-ce
        restart: always
        ports:
            - 8000:8000
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

  app:
    build: .
    working_dir: /app
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: sh -c "npm install && node server.js"
    restart: unless-stopped
    portainer_data: